/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioSlugRouteImport } from './routes/$portfolioSlug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as OnlineTuitionRouteImport } from './routes/online-tuition'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as PortfolioSlugIndexRouteImport } from './routes/$portfolioSlug/index'
import { Route as PortfolioSlugSplatRouteImport } from './routes/$portfolioSlug/$'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as SuperAdminGuardRouteImport } from './routes/super-admin/_guard'
import { Route as SuperAdminLoginRouteImport } from './routes/super-admin/login'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminSectionRouteImport } from './routes/_authenticated/admin.$section'
import { Route as SuperAdminGuardIndexRouteImport } from './routes/super-admin/_guard/index'
import { Route as SuperAdminGuardAdminsRouteImport } from './routes/super-admin/_guard/admins'
import { Route as SuperAdminGuardBackupsRouteImport } from './routes/super-admin/_guard/backups'
import { Route as SuperAdminGuardClientsRouteImport } from './routes/super-admin/_guard/clients'
import { Route as SuperAdminGuardDomainsRouteImport } from './routes/super-admin/_guard/domains'
import { Route as SuperAdminGuardLogsRouteImport } from './routes/super-admin/_guard/logs'
import { Route as SuperAdminGuardMediaRouteImport } from './routes/super-admin/_guard/media'
import { Route as SuperAdminGuardProfileRouteImport } from './routes/super-admin/_guard/profile'
import { Route as SuperAdminGuardSettingsRouteImport } from './routes/super-admin/_guard/settings'
import { Route as SuperAdminGuardPortfoliosIndexRouteImport } from './routes/super-admin/_guard/portfolios/index'
import { Route as SuperAdminGuardPortfoliosIdRouteImport } from './routes/super-admin/_guard/portfolios/$id'
import { Route as SuperAdminGuardPortfoliosNewRouteImport } from './routes/super-admin/_guard/portfolios/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$portfolioSlug',
  path: '/$portfolioSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineTuitionRoute = OnlineTuitionRouteImport.update({
  id: '/online-tuition',
  path: '/online-tuition',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugIndexRoute = PortfolioSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioSlugRoute,
} as any)
const PortfolioSlugSplatRoute = PortfolioSlugSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PortfolioSlugRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SuperAdminGuardRoute = SuperAdminGuardRouteImport.update({
  id: '/_guard',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminLoginRoute = SuperAdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SuperAdminRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSectionRoute =
  AuthenticatedAdminSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const SuperAdminGuardIndexRoute = SuperAdminGuardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminGuardRoute,
} as any)
const SuperAdminGuardAdminsRoute = SuperAdminGuardAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => SuperAdminGuardRoute,
} as any)
const SuperAdminGuardBackupsRoute = SuperAdminGuardBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => SuperAdminGuardRoute,
} as any)
const SuperAdminGuardClientsRoute = SuperAdminGuardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => SuperAdminGuardRoute,
} as any)
const SuperAdminGuardDomainsRoute = SuperAdminGuardDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => SuperAdminGuardRoute,
} as any)
const SuperAdminGuardLogsRoute = SuperAdminGuardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => SuperAdminGuardRoute,
} as any)
const SuperAdminGuardMediaRoute = SuperAdminGuardMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => SuperAdminGuardRoute,
} as any)
const SuperAdminGuardProfileRoute = SuperAdminGuardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SuperAdminGuardRoute,
} as any)
const SuperAdminGuardSettingsRoute = SuperAdminGuardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperAdminGuardRoute,
} as any)
const SuperAdminGuardPortfoliosIndexRoute =
  SuperAdminGuardPortfoliosIndexRouteImport.update({
    id: '/portfolios/',
    path: '/portfolios/',
    getParentRoute: () => SuperAdminGuardRoute,
  } as any)
const SuperAdminGuardPortfoliosIdRoute =
  SuperAdminGuardPortfoliosIdRouteImport.update({
    id: '/portfolios/$id',
    path: '/portfolios/$id',
    getParentRoute: () => SuperAdminGuardRoute,
  } as any)
const SuperAdminGuardPortfoliosNewRoute =
  SuperAdminGuardPortfoliosNewRouteImport.update({
    id: '/portfolios/new',
    path: '/portfolios/new',
    getParentRoute: () => SuperAdminGuardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$portfolioSlug': typeof PortfolioSlugRouteWithChildren
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/online-tuition': typeof OnlineTuitionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/subjects': typeof SubjectsRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/$portfolioSlug/$': typeof PortfolioSlugSplatRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/$portfolioSlug/': typeof PortfolioSlugIndexRoute
  '/admin/$section': typeof AuthenticatedAdminSectionRoute
  '/super-admin/admins': typeof SuperAdminGuardAdminsRoute
  '/super-admin/backups': typeof SuperAdminGuardBackupsRoute
  '/super-admin/clients': typeof SuperAdminGuardClientsRoute
  '/super-admin/domains': typeof SuperAdminGuardDomainsRoute
  '/super-admin/logs': typeof SuperAdminGuardLogsRoute
  '/super-admin/media': typeof SuperAdminGuardMediaRoute
  '/super-admin/profile': typeof SuperAdminGuardProfileRoute
  '/super-admin/settings': typeof SuperAdminGuardSettingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/super-admin/': typeof SuperAdminGuardIndexRoute
  '/super-admin/portfolios/$id': typeof SuperAdminGuardPortfoliosIdRoute
  '/super-admin/portfolios/new': typeof SuperAdminGuardPortfoliosNewRoute
  '/super-admin/portfolios/': typeof SuperAdminGuardPortfoliosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/online-tuition': typeof OnlineTuitionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/subjects': typeof SubjectsRoute
  '/super-admin': typeof SuperAdminGuardIndexRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/$portfolioSlug/$': typeof PortfolioSlugSplatRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/$portfolioSlug': typeof PortfolioSlugIndexRoute
  '/admin/$section': typeof AuthenticatedAdminSectionRoute
  '/super-admin/admins': typeof SuperAdminGuardAdminsRoute
  '/super-admin/backups': typeof SuperAdminGuardBackupsRoute
  '/super-admin/clients': typeof SuperAdminGuardClientsRoute
  '/super-admin/domains': typeof SuperAdminGuardDomainsRoute
  '/super-admin/logs': typeof SuperAdminGuardLogsRoute
  '/super-admin/media': typeof SuperAdminGuardMediaRoute
  '/super-admin/profile': typeof SuperAdminGuardProfileRoute
  '/super-admin/settings': typeof SuperAdminGuardSettingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/super-admin/portfolios/$id': typeof SuperAdminGuardPortfoliosIdRoute
  '/super-admin/portfolios/new': typeof SuperAdminGuardPortfoliosNewRoute
  '/super-admin/portfolios': typeof SuperAdminGuardPortfoliosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$portfolioSlug': typeof PortfolioSlugRouteWithChildren
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/online-tuition': typeof OnlineTuitionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/subjects': typeof SubjectsRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/$portfolioSlug/$': typeof PortfolioSlugSplatRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/super-admin/_guard': typeof SuperAdminGuardRouteWithChildren
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/$portfolioSlug/': typeof PortfolioSlugIndexRoute
  '/_authenticated/admin/$section': typeof AuthenticatedAdminSectionRoute
  '/super-admin/_guard/admins': typeof SuperAdminGuardAdminsRoute
  '/super-admin/_guard/backups': typeof SuperAdminGuardBackupsRoute
  '/super-admin/_guard/clients': typeof SuperAdminGuardClientsRoute
  '/super-admin/_guard/domains': typeof SuperAdminGuardDomainsRoute
  '/super-admin/_guard/logs': typeof SuperAdminGuardLogsRoute
  '/super-admin/_guard/media': typeof SuperAdminGuardMediaRoute
  '/super-admin/_guard/profile': typeof SuperAdminGuardProfileRoute
  '/super-admin/_guard/settings': typeof SuperAdminGuardSettingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/super-admin/_guard/': typeof SuperAdminGuardIndexRoute
  '/super-admin/_guard/portfolios/$id': typeof SuperAdminGuardPortfoliosIdRoute
  '/super-admin/_guard/portfolios/new': typeof SuperAdminGuardPortfoliosNewRoute
  '/super-admin/_guard/portfolios/': typeof SuperAdminGuardPortfoliosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$portfolioSlug'
    | '/about'
    | '/achievements'
    | '/auth'
    | '/contact'
    | '/gallery'
    | '/online-tuition'
    | '/reset-password'
    | '/subjects'
    | '/super-admin'
    | '/testimonials'
    | '/thank-you'
    | '/$portfolioSlug/$'
    | '/admin'
    | '/super-admin/login'
    | '/$portfolioSlug/'
    | '/admin/$section'
    | '/super-admin/admins'
    | '/super-admin/backups'
    | '/super-admin/clients'
    | '/super-admin/domains'
    | '/super-admin/logs'
    | '/super-admin/media'
    | '/super-admin/profile'
    | '/super-admin/settings'
    | '/admin/'
    | '/super-admin/'
    | '/super-admin/portfolios/$id'
    | '/super-admin/portfolios/new'
    | '/super-admin/portfolios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/auth'
    | '/contact'
    | '/gallery'
    | '/online-tuition'
    | '/reset-password'
    | '/subjects'
    | '/super-admin'
    | '/testimonials'
    | '/thank-you'
    | '/$portfolioSlug/$'
    | '/super-admin/login'
    | '/$portfolioSlug'
    | '/admin/$section'
    | '/super-admin/admins'
    | '/super-admin/backups'
    | '/super-admin/clients'
    | '/super-admin/domains'
    | '/super-admin/logs'
    | '/super-admin/media'
    | '/super-admin/profile'
    | '/super-admin/settings'
    | '/admin'
    | '/super-admin/portfolios/$id'
    | '/super-admin/portfolios/new'
    | '/super-admin/portfolios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$portfolioSlug'
    | '/about'
    | '/achievements'
    | '/auth'
    | '/contact'
    | '/gallery'
    | '/online-tuition'
    | '/reset-password'
    | '/subjects'
    | '/super-admin'
    | '/testimonials'
    | '/thank-you'
    | '/$portfolioSlug/$'
    | '/_authenticated/admin'
    | '/super-admin/_guard'
    | '/super-admin/login'
    | '/$portfolioSlug/'
    | '/_authenticated/admin/$section'
    | '/super-admin/_guard/admins'
    | '/super-admin/_guard/backups'
    | '/super-admin/_guard/clients'
    | '/super-admin/_guard/domains'
    | '/super-admin/_guard/logs'
    | '/super-admin/_guard/media'
    | '/super-admin/_guard/profile'
    | '/super-admin/_guard/settings'
    | '/_authenticated/admin/'
    | '/super-admin/_guard/'
    | '/super-admin/_guard/portfolios/$id'
    | '/super-admin/_guard/portfolios/new'
    | '/super-admin/_guard/portfolios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PortfolioSlugRoute: typeof PortfolioSlugRouteWithChildren
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  OnlineTuitionRoute: typeof OnlineTuitionRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SubjectsRoute: typeof SubjectsRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  TestimonialsRoute: typeof TestimonialsRoute
  ThankYouRoute: typeof ThankYouRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$portfolioSlug': {
      id: '/$portfolioSlug'
      path: '/$portfolioSlug'
      fullPath: '/$portfolioSlug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-tuition': {
      id: '/online-tuition'
      path: '/online-tuition'
      fullPath: '/online-tuition'
      preLoaderRoute: typeof OnlineTuitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$portfolioSlug/': {
      id: '/$portfolioSlug/'
      path: '/'
      fullPath: '/$portfolioSlug/'
      preLoaderRoute: typeof PortfolioSlugIndexRouteImport
      parentRoute: typeof PortfolioSlugRoute
    }
    '/$portfolioSlug/$': {
      id: '/$portfolioSlug/$'
      path: '/$'
      fullPath: '/$portfolioSlug/$'
      preLoaderRoute: typeof PortfolioSlugSplatRouteImport
      parentRoute: typeof PortfolioSlugRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/super-admin/_guard': {
      id: '/super-admin/_guard'
      path: ''
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminGuardRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/login': {
      id: '/super-admin/login'
      path: '/login'
      fullPath: '/super-admin/login'
      preLoaderRoute: typeof SuperAdminLoginRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/$section': {
      id: '/_authenticated/admin/$section'
      path: '/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AuthenticatedAdminSectionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/super-admin/_guard/': {
      id: '/super-admin/_guard/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminGuardIndexRouteImport
      parentRoute: typeof SuperAdminGuardRoute
    }
    '/super-admin/_guard/admins': {
      id: '/super-admin/_guard/admins'
      path: '/admins'
      fullPath: '/super-admin/admins'
      preLoaderRoute: typeof SuperAdminGuardAdminsRouteImport
      parentRoute: typeof SuperAdminGuardRoute
    }
    '/super-admin/_guard/backups': {
      id: '/super-admin/_guard/backups'
      path: '/backups'
      fullPath: '/super-admin/backups'
      preLoaderRoute: typeof SuperAdminGuardBackupsRouteImport
      parentRoute: typeof SuperAdminGuardRoute
    }
    '/super-admin/_guard/clients': {
      id: '/super-admin/_guard/clients'
      path: '/clients'
      fullPath: '/super-admin/clients'
      preLoaderRoute: typeof SuperAdminGuardClientsRouteImport
      parentRoute: typeof SuperAdminGuardRoute
    }
    '/super-admin/_guard/domains': {
      id: '/super-admin/_guard/domains'
      path: '/domains'
      fullPath: '/super-admin/domains'
      preLoaderRoute: typeof SuperAdminGuardDomainsRouteImport
      parentRoute: typeof SuperAdminGuardRoute
    }
    '/super-admin/_guard/logs': {
      id: '/super-admin/_guard/logs'
      path: '/logs'
      fullPath: '/super-admin/logs'
      preLoaderRoute: typeof SuperAdminGuardLogsRouteImport
      parentRoute: typeof SuperAdminGuardRoute
    }
    '/super-admin/_guard/media': {
      id: '/super-admin/_guard/media'
      path: '/media'
      fullPath: '/super-admin/media'
      preLoaderRoute: typeof SuperAdminGuardMediaRouteImport
      parentRoute: typeof SuperAdminGuardRoute
    }
    '/super-admin/_guard/profile': {
      id: '/super-admin/_guard/profile'
      path: '/profile'
      fullPath: '/super-admin/profile'
      preLoaderRoute: typeof SuperAdminGuardProfileRouteImport
      parentRoute: typeof SuperAdminGuardRoute
    }
    '/super-admin/_guard/settings': {
      id: '/super-admin/_guard/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperAdminGuardSettingsRouteImport
      parentRoute: typeof SuperAdminGuardRoute
    }
    '/super-admin/_guard/portfolios/': {
      id: '/super-admin/_guard/portfolios/'
      path: '/portfolios'
      fullPath: '/super-admin/portfolios/'
      preLoaderRoute: typeof SuperAdminGuardPortfoliosIndexRouteImport
      parentRoute: typeof SuperAdminGuardRoute
    }
    '/super-admin/_guard/portfolios/$id': {
      id: '/super-admin/_guard/portfolios/$id'
      path: '/portfolios/$id'
      fullPath: '/super-admin/portfolios/$id'
      preLoaderRoute: typeof SuperAdminGuardPortfoliosIdRouteImport
      parentRoute: typeof SuperAdminGuardRoute
    }
    '/super-admin/_guard/portfolios/new': {
      id: '/super-admin/_guard/portfolios/new'
      path: '/portfolios/new'
      fullPath: '/super-admin/portfolios/new'
      preLoaderRoute: typeof SuperAdminGuardPortfoliosNewRouteImport
      parentRoute: typeof SuperAdminGuardRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminSectionRoute: typeof AuthenticatedAdminSectionRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminSectionRoute: AuthenticatedAdminSectionRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PortfolioSlugRouteChildren {
  PortfolioSlugSplatRoute: typeof PortfolioSlugSplatRoute
  PortfolioSlugIndexRoute: typeof PortfolioSlugIndexRoute
}

const PortfolioSlugRouteChildren: PortfolioSlugRouteChildren = {
  PortfolioSlugSplatRoute: PortfolioSlugSplatRoute,
  PortfolioSlugIndexRoute: PortfolioSlugIndexRoute,
}

const PortfolioSlugRouteWithChildren = PortfolioSlugRoute._addFileChildren(
  PortfolioSlugRouteChildren,
)

interface SuperAdminGuardRouteChildren {
  SuperAdminGuardAdminsRoute: typeof SuperAdminGuardAdminsRoute
  SuperAdminGuardBackupsRoute: typeof SuperAdminGuardBackupsRoute
  SuperAdminGuardClientsRoute: typeof SuperAdminGuardClientsRoute
  SuperAdminGuardDomainsRoute: typeof SuperAdminGuardDomainsRoute
  SuperAdminGuardLogsRoute: typeof SuperAdminGuardLogsRoute
  SuperAdminGuardMediaRoute: typeof SuperAdminGuardMediaRoute
  SuperAdminGuardProfileRoute: typeof SuperAdminGuardProfileRoute
  SuperAdminGuardSettingsRoute: typeof SuperAdminGuardSettingsRoute
  SuperAdminGuardIndexRoute: typeof SuperAdminGuardIndexRoute
  SuperAdminGuardPortfoliosIdRoute: typeof SuperAdminGuardPortfoliosIdRoute
  SuperAdminGuardPortfoliosNewRoute: typeof SuperAdminGuardPortfoliosNewRoute
  SuperAdminGuardPortfoliosIndexRoute: typeof SuperAdminGuardPortfoliosIndexRoute
}

const SuperAdminGuardRouteChildren: SuperAdminGuardRouteChildren = {
  SuperAdminGuardAdminsRoute: SuperAdminGuardAdminsRoute,
  SuperAdminGuardBackupsRoute: SuperAdminGuardBackupsRoute,
  SuperAdminGuardClientsRoute: SuperAdminGuardClientsRoute,
  SuperAdminGuardDomainsRoute: SuperAdminGuardDomainsRoute,
  SuperAdminGuardLogsRoute: SuperAdminGuardLogsRoute,
  SuperAdminGuardMediaRoute: SuperAdminGuardMediaRoute,
  SuperAdminGuardProfileRoute: SuperAdminGuardProfileRoute,
  SuperAdminGuardSettingsRoute: SuperAdminGuardSettingsRoute,
  SuperAdminGuardIndexRoute: SuperAdminGuardIndexRoute,
  SuperAdminGuardPortfoliosIdRoute: SuperAdminGuardPortfoliosIdRoute,
  SuperAdminGuardPortfoliosNewRoute: SuperAdminGuardPortfoliosNewRoute,
  SuperAdminGuardPortfoliosIndexRoute: SuperAdminGuardPortfoliosIndexRoute,
}

const SuperAdminGuardRouteWithChildren = SuperAdminGuardRoute._addFileChildren(
  SuperAdminGuardRouteChildren,
)

interface SuperAdminRouteChildren {
  SuperAdminGuardRoute: typeof SuperAdminGuardRouteWithChildren
  SuperAdminLoginRoute: typeof SuperAdminLoginRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminGuardRoute: SuperAdminGuardRouteWithChildren,
  SuperAdminLoginRoute: SuperAdminLoginRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PortfolioSlugRoute: PortfolioSlugRouteWithChildren,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  OnlineTuitionRoute: OnlineTuitionRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SubjectsRoute: SubjectsRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  TestimonialsRoute: TestimonialsRoute,
  ThankYouRoute: ThankYouRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
